### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)
print(vector)

[0.76576748 0.47606631 0.63201925 0.81367247 0.11851844 0.6202868
 0.59351451 0.34577103 0.83389701 0.88442855]


In [4]:
A= np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])

In [8]:
print("Оригінальна матриця A", A,sep='\n')

Оригінальна матриця A
[[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [9]:
vector_plus_10 = np.round(vector + 10, 2)
print(vector_plus_10)


[10.77 10.48 10.63 10.81 10.12 10.62 10.59 10.35 10.83 10.88]


In [12]:
vector_times_2 = vector * 2
print(vector_times_2)


[1.53153497 0.95213262 1.26403851 1.62734494 0.23703688 1.2405736
 1.18702901 0.69154206 1.66779401 1.76885709]


In [13]:
vector_squared = vector ** 2
print(vector_squared)


[0.58639984 0.22663913 0.39944834 0.66206289 0.01404662 0.38475571
 0.35225947 0.1195576  0.69538422 0.78221385]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [15]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [19]:
result_matrix=np.dot(A, B)#не та розмірність
print('Результуюча матриця', result_matrix, sep='\n')

Результуюча матриця
[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


In [20]:
A_T = A.T #спробуємо через транспонування
B_T = B.T

print("A_T shape:", A_T.shape)
print("B_T shape:", B_T.shape)


A_T shape: (2, 3)
B_T shape: (3, 2)


In [23]:
result_matrix = np.dot(A_T, B_T)
print("Result matrix 2x2", result_matrix, sep='\n')


Result matrix 2x2
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [25]:
C = np.array([
    [2],
    [5]
])

result_C = np.dot(result_matrix, C)
print("Множення на вектор С", result_C, sep='\n')


Result matrix 2x2 nmultiplying with vector
[[2.4732]
 [2.4634]]


In [26]:
D = np.array([
    [1, 4],
    [3, 2]
])

result_D = np.dot(result_matrix, D)
print("Множення на матирцю D", result_D, sep='\n')


Множення на матирцю D
[[1.3383 3.3192]
 [1.374  2.65  ]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [27]:
#1
result_matrix_T = result_matrix.T
print(" Транспонована result_matrix", result_matrix_T, sep='\n')
print("Shape:", result_matrix_T.shape)


 Транспонована result_matrix
[[0.7281 0.5202]
 [0.2034 0.2846]]
Shape: (2, 2)


In [31]:
#2
vector.shape

(10,)

In [29]:
vector_T = vector.T
print("vector_T:", vector_T)
print("Shape:", vector_T.shape)


vector_T: [0.76576748 0.47606631 0.63201925 0.81367247 0.11851844 0.6202868
 0.59351451 0.34577103 0.83389701 0.88442855]
Shape: (10,)


В даному випадку  вектор не має розмірності рядків/стовпців, він має форму. Тому транспонування нічого не змінює.

In [34]:
#3
column_vector = np.expand_dims(vector, axis=1)
print("column_vector", column_vector, sep='\n')
print("Shape:", column_vector.shape)


column_vector
[[0.76576748]
 [0.47606631]
 [0.63201925]
 [0.81367247]
 [0.11851844]
 [0.6202868 ]
 [0.59351451]
 [0.34577103]
 [0.83389701]
 [0.88442855]]
Shape: (10, 1)


In [36]:
column_vector_T=column_vector.T
print("column_vector_T", column_vector_T, sep='\n')
print("Shape:", column_vector_T.shape)

column_vector_T
[[0.76576748 0.47606631 0.63201925 0.81367247 0.11851844 0.6202868
  0.59351451 0.34577103 0.83389701 0.88442855]]
Shape: (1, 10)
