1. Створення масивів

Створіть (кожен пункт оцінюється в 0.5 бала):

Масив зі списку [5, 15, 25, 35, 45]
Масив з нулів розміром 7
Масив з одиниць розміром 6
Масив з числами від 10 до 19 використовуючи np.arange()

In [3]:
import numpy as np

In [4]:
arr=np.array([5, 15, 25, 35, 45])

In [5]:
print(arr)

[ 5 15 25 35 45]


In [6]:
arr

array([ 5, 15, 25, 35, 45])

In [9]:
zeros=np.zeros(7)

In [10]:
zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
ones = np.ones(6)

In [12]:
ones

array([1., 1., 1., 1., 1., 1.])

In [17]:
range_arr = np.arange(1, 20)

In [18]:
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])


**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [19]:
array=np.array([12, 24, 36, 48, 60])

In [20]:
array

array([12, 24, 36, 48, 60])

In [21]:
print(array*2)

[ 24  48  72  96 120]


In [22]:
print(array+10)

[22 34 46 58 70]


In [23]:
print(array**2)

[ 144  576 1296 2304 3600]


In [26]:
print(np.sqrt(array))

[3.46410162 4.89897949 6.         6.92820323 7.74596669]



**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [30]:
data=np.array ([18, 27, 33, 41, 52, 68, 79])

In [31]:
print(data)

[18 27 33 41 52 68 79]


In [32]:
print (np.mean(data))

45.42857142857143


In [33]:
print (np.min(data))

18


In [34]:
print (np.max(data))

79


In [35]:
print (np.sum(data))

318



**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [36]:
arr=np.array([15, 22, 35, 44, 58, 67])

In [37]:
arr

array([15, 22, 35, 44, 58, 67])

In [46]:
print(arr[0])
print(arr[-1])
print(arr[1:3])
mask=arr > 40
arr[mask]


15
67
[22 35]


array([44, 58, 67])

In [ ]:

**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [57]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [58]:
matrix.shape


(3, 3)

In [59]:
print (matrix[0, :])

[2 4 6]


In [60]:
print (matrix [:, 1])

[ 4 10 16]


In [65]:
print(np.sum(matrix))

90


In [66]:
print(np.mean(matrix))

10.0
